
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: epub_reader_development
  username: reed
  password: reed

production:
  adapter: postgresql
  pool: 5
  database: epub_reader_production
  username: reed
  password: reed
